"""add keywords to job_posts

Revision ID: 00c3847fe69f
Revises: a691693c30ee
Create Date: 2026-06-25 12:38:19.815565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c3847fe69f'
down_revision: Union[str, None] = 'a691693c30ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('keywords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'keywords')
    # ### end Alembic commands ###
